# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/midimaster21b/prj/tech_challenge/tech_challenge.srcs/sources_1/bd/design_1/ip/design_1_adc_adapter_top_0_0/design_1_adc_adapter_top_0_0.xci
# IP: The module: 'design_1_adc_adapter_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/midimaster21b/prj/tech_challenge/tech_challenge.gen/sources_1/bd/design_1/ip/design_1_adc_adapter_top_0_0/src/sample_fifo/sample_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sample_fifo || ORIG_REF_NAME==sample_fifo} -quiet] -quiet

# IP: /home/midimaster21b/prj/tech_challenge/tech_challenge.srcs/sources_1/bd/design_1/ip/design_1_adc_adapter_top_0_0/design_1_adc_adapter_top_0_0.xci
# IP: The module: 'design_1_adc_adapter_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/midimaster21b/prj/tech_challenge/tech_challenge.gen/sources_1/bd/design_1/ip/design_1_adc_adapter_top_0_0/src/sample_fifo/sample_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sample_fifo || ORIG_REF_NAME==sample_fifo} -quiet] -quiet
